name: blue_alliance_client
description: A client wrapper for API calls to The Blue Alliance.
version: 0.1.0
homepage: https://github.com/Quantaly/blue_alliance_client

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  http: ^0.12.0
  path: ^1.6.0

dev_dependencies:
  test: ^1.6.0

  quantaly_lints:
    git:
      url: https://github.com/Quantaly/dart_lints/
